services:
  - type: web
    name: banco-central-nodo1
    runtime: docker
    region: virginia
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    autoDeployTrigger: off
    envVars:
      - key: APP_NAME
        value: "BancoCentral"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        value: "aws-0-us-east-1.pooler.supabase.com"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "postgres"
      - key: DB_USERNAME
        value: postgres.rtfdnrwcjwovpplmfthc
      - key: DB_SSLMODE
        value: require
      - key: DB_PASSWORD
        sync: false
      - key: SUPABASE_URL
        value: https://rtfdnrwcjwovpplmfthc.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
